### ISSUE TITLE
BUG-000120452 The Copy Feature tool in ArcGIS Pro 2.3.1 creates a copy with an offset of the original feature class when the coordinate system from Environment changes.

### ISSUE THREAD

**Issue by kev10076** [bsvensson/dummy-repo#14]
<div></div>
<span><b>Salesforce ID:</b> <a href="https://dqaweb2/SFTriage?sfid=BUG-000120452">BUG-000120452</a></span><br/>
<span><b>Salesforce Submitter:</b> Roy Miller</span><br/>
<span><b>Salesforce Submit Date:</b> 2/28/2019 11:53 PM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> <p>Save the copy a second time if ArcGIS Pro just restarted and look for offsets.</p></span><br/>
<span><b>Product:</b> Test Product</span><br/>
<span><b>Functional Category:</b> Test Functional Area</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 2.3.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>

**Comment by kory7554** [comment]
Test closing to see if it picks up in the status sidebar of the app.
